const data = {
  products: [
    {
      name: 'Jordan 1',
      slug: 'Jordan-1',
      category: 'Adidasi',
      image: '/images/p1.jpg',
      price: 800,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'foarte buni adidasi',
    },
    {
      name: 'Nike 970',
      slug: 'Nike-970',
      category: 'Adidasi',
      image: '/images/p2.jpg',
      price: 1000,
      countInStock: 2,
      brand: 'Nike',
      rating: 5,
      numReviews: 2,
      description: 'destul de rai',
    },
    {
      name: 'Adidas Ozrah',
      slug: 'Adidas-Ozrah',
      category: 'Adidasi',
      image: '/images/p3.jpg',
      price: 550,
      countInStock: 22,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 27,
      description: 'excelenti',
    },
    {
      name: 'Adidas Ozelia',
      slug: 'Adidas-Ozelia',
      category: 'Adidasi',
      image: '/images/p4.jpg',
      price: 420,
      countInStock: 3,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 4,
      description: 'sunt ok',
    },
  ],
};

export default data;
